config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index', :as => 'home'
  get 'grades' => 'home#grades', :as => 'grades'
  get 'help' => 'help#index', :as => 'help'
  get 'reports' => 'reports#index', :as => 'reports'

  devise_for :users, :path_prefix => 'security'

  resources :announcements, :path => 'admin/announcements'
  resources :districts, :path => 'admin/districts'
  resources :grades, :path => 'admin/grades'
  resources :roles, :path => 'admin/roles'
  resources :users, :path => 'admin/users'
  resources :application_settings, :path => 'admin/settings'
  resources :staff_members, :path => 'admin/staff'

  resources :schools, :path => 'admin/schools' do
    resources :school_years, :path => 'years'
  end

  resources :students do
    get 'delete'
    post 'delete'

    resources :student_addresses, :path => 'addresses', :as => 'addresses' do
      resources :student_relationships, :path => 'contacts', :as => 'contacts'
    end

    resources :student_notes, :path => 'notes', :as => 'notes'
    resources :student_enrollments, :path => 'enrollments', :as => 'enrollments'

  end

end

app/models/announcement.rb
class Announcement < ApplicationRecord

  scope :active, -> { where('start_date <= ? and ((end_date is null) or (end_date >= ?))', DateTime.now.at_beginning_of_day, DateTime.now.at_beginning_of_day) }
  scope :active_flagged, -> { where('start_date <= ? and ((end_date is null) or (end_date >= ?)) and is_flagged = true', DateTime.now.at_beginning_of_day, DateTime.now.at_beginning_of_day) }

  validates :title, presence: true, length: {maximum: 50}
  validates :body, presence: true
  validates :start_date, presence: true

end

app/controllers/announcements_controller.rb
class AnnouncementsController < ControlPanelController
  def index
    @announcements = Announcement.all
  end

  def new
    @announcement = Announcement.new
  end

  def edit
    get
  end

  def show
    get
  end

  def create
    @announcement = Announcement.new(announcement_params)

    if @announcement.save
      redirect_to @announcement
    else
      render 'new'
    end
  end

  def update
    get

    if @announcement.update(announcement_params)
      redirect_to @announcement
    else
      render 'edit'
    end
  end

  def destroy
    get
    @announcement.destroy
    redirect_to announcements_path
  end

  private

  def get
    @announcement = Announcement.find(params[:id])
  end

  def announcement_params
    params.require(:announcement).permit(:id, :title, :body, :start_date, :end_date, :is_flagged)
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/views/announcements/_form.html.haml
.form-group
  = f.label :title
  = f.text_field :title, :class => 'form-control', :placeholder => 'Title', disabled: disabled

.form-group
  = f.label :body
  = f.text_area :body, :class => 'form-control', :placeholder => 'Body', disabled: disabled

.form-group
  = f.label :start_date
  = f.text_field :start_date, :class => 'form-control', :placeholder => 'Start date', disabled: disabled

.form-group
  = f.label :end_date
  = f.text_field :end_date, :class => 'form-control', :placeholder => 'End date', disabled: disabled

.form-group
  = f.label :is_flagged
  = f.text_field :is_flagged, :class => 'form-control', :placeholder => 'Is flagged', disabled: disabled

app/views/announcements/edit.html.haml
%h3 Edit Announcement
.row
  .col-md-12
    = form_for @announcement, url: announcement_path(@announcement), method: :patch, :html => { :class => '' } do |f|
      .panel.panel-primary
        .panel-heading
          %h3.panel-title Information
        .panel-body
          = error_messages_for 'announcement'
          = render :partial => 'announcements/form', :locals => {:f => f, :disabled => false}
        .panel-footer
          = link_to 'Cancel', announcement_path(@announcement), :class => 'btn btn-default'
          = f.submit 'Save Changes', :class => 'btn btn-success'

app/views/announcements/index.html.haml
- page_title 'Announcements', 'Administration'
%h3
  = fa_icon 'bullhorn'
  Announcements

.row
  .col-lg-9
    .form-group.mb-xl
      %input.form-control.mb{:placeholder => 'Search by title', :type => 'text'}
      .clearfix
        %button.pull-left.btn.btn-default{:type => 'button'} Search
        .pull-right
          %label.checkbox-inline.c-checkbox
            %input#inlineCheckbox10{:type => 'checkbox', :value => 'option1'}
            = succeed 'Include expired announcements' do
              %span.fa.fa-check
    .table-responsive
      %table.table.table-bordered.table-striped
        %thead
          %tr
            %th.action-column
            %th Title
            %th Body
            %th Duration
        %tbody
          - @announcements.each do |a|
            %tr
              %td= link_to 'Select', announcement_path(a)
              %td= a.title
              %td= a.body
              %td= display_thur_dates(a.start_date, a.end_date)
  .col-lg-3
    .panel.panel-default
      .panel-heading
        %h3.panel-title Filters
      .panel-body
        .form-group
          %label Start Date
          %br
          %input{:type => 'text', :class => 'form-control'}
        .form-group
          %label End Date
          %br
          %input{:type => 'text', :class => 'form-control'}
        %button.btn.btn-default.btn-lg Apply

= link_to 'New announcement', new_announcement_path, :class => 'btn btn-primary'

app/views/announcements/new.html.haml
%h3 New Announcement
.row
  .col-md-12
    = form_for :announcement, url: announcements_path, :html => { :class => '' } do |f|
      .panel.panel-primary
        .panel-heading
          %h3.panel-title Information
        .panel-body
          = error_messages_for 'announcement'
          = render :partial => 'announcements/form', :locals => {:f => f, :disabled => false}
        .panel-footer
          = link_to 'Cancel', announcements_path, :class => 'btn btn-default'
          = f.submit 'Create', :class => 'btn btn-success'

app/views/announcements/show.html.haml
%h3 Announcement
.row
  .col-md-12
    = form_for :announcement, url: announcements_path, :html => { :class => '' } do |f|
      .panel.panel-primary
        .panel-heading
          %h3.panel-title Information
        .panel-body
          = error_messages_for 'announcement'
          = render :partial => 'announcements/form', :locals => {:f => f, :disabled => true}
        .panel-footer
          = link_to 'Cancel', announcements_path, :class => 'btn btn-default'
          = link_to 'Edit', edit_announcement_path(@announcement), :class => 'btn btn-primary'