config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index', :as => 'home'
  get 'grades' => 'home#grades', :as => 'grades'
  get 'help' => 'help#index', :as => 'help'
  get 'reports' => 'reports#index', :as => 'reports'

  devise_for :users, :path_prefix => 'security'

  resources :announcements, :path => 'admin/announcements'
  resources :districts, :path => 'admin/districts'
  resources :grades, :path => 'admin/grades'
  resources :roles, :path => 'admin/roles'
  resources :users, :path => 'admin/users'
  resources :application_settings, :path => 'admin/settings'
  resources :staff_members, :path => 'admin/staff'

  resources :schools, :path => 'admin/schools' do
    resources :school_years, :path => 'years'
  end

  resources :students do
    get 'delete'
    post 'delete'

    resources :student_addresses, :path => 'addresses', :as => 'addresses' do
      resources :student_relationships, :path => 'contacts', :as => 'contacts'
    end

    resources :student_notes, :path => 'notes', :as => 'notes'
    resources :student_enrollments, :path => 'enrollments', :as => 'enrollments'

  end

end

app/models/student_relationship.rb
class StudentRelationship < ApplicationRecord

  default_scope { order(:contact_order) }

  belongs_to :student_address
  belongs_to :person

end

app/controllers/student_relationships_controller.rb
class StudentRelationshipsController < ApplicationController
  def show
    get
  end

  def new
    @relationship = StudentRelationship.new
    @relationship.student_address = StudentAddress.includes(:student).find(params[:address_id])
  end

  def edit
    get
  end

  def create
    @relationship = StudentRelationship.new(relationship_params)

    if @relationship.save
      redirect_to @relationship.student_address.student
    else
      render 'new'
    end
  end

  def update
    get

    if @relationship.update(relationship_params)
      redirect_to @relationship.student_address.student
    else
      render 'edit'
    end
  end

  def destroy
    get
  end

  private

  def get
    @relationship = StudentRelationship.includes(:person, student_address: [:student, :address]).find(params[:id])
  end

  def relationship_params
    params.require(:student_relationships).permit(:id, :student_address_id, :person_id, :has_custody, :is_emergency, :relation, :contact_order,
                                                  { :person_attributes => [:id, :first_name, :middle_name, :last_name, :email_address] },
                                                  { :student_addresses_attributes => [:id, :student_id, :address_id, :is_mailing, :is_residential, :is_bus_pickup, :is_bus_drop_off,
                                                                                      { :address_attributes => [:id, :street, :city, :state, :zip_code, :phone_number] } ] })
  end
end

app/helpers/student_relationship_helper.rb
module StudentRelationshipHelper
end

app/views/student_relationships/edit.html.haml
%h3 Edit Grade Level

= form_for @relationship, url: student_address_contacts_path(@relationship), method: :patch, :html => { :class => '' } do |f|
  .panel.panel-primary
    .panel-heading
      Basic Information
    .panel-body
      = error_messages_for 'relationship'
      = render :partial => 'student_relationships/form', :locals => { :f => f }
    .panel-footer
      = link_to 'Cancel', grades_path, :class => 'btn btn-default'
      = f.submit 'Save Changes', :class => 'btn btn-success'

app/views/student_relationships/new.html.haml
- page_title @relationship.student_address.student.formatted_full_name, 'New Contact'

= render :partial => 'students/common/header', :locals => {:student => @relationship.student_address.student }

.row
  .col-sm-2.col-xs-12
    = render :partial => 'students/common/sidebar', :locals => {:student => @relationship.student_address.student }
  .col-sm-10.col-xs-12
    = form_for @relationship, url: student_address_contacts_path(@relationship.student_address.student), :html => { :class => '' } do |f|
      .panel.panel-primary
        .panel-heading
          %h3.panel-title New Relationship
        .panel-body
          = error_messages_for 'relationship'
          = render :partial => 'student_relationships/form', :locals => { :f => f }
        .panel-footer
          = link_to 'Cancel', student_addresses_path(@relationship.student_address.student), :class => 'btn btn-default'
          = f.submit 'Create', :class => 'btn btn-success'