config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index', :as => 'home'
  get 'grades' => 'home#grades', :as => 'grades'
  get 'help' => 'help#index', :as => 'help'
  get 'reports' => 'reports#index', :as => 'reports'

  devise_for :users, :path_prefix => 'security'

  resources :announcements, :path => 'admin/announcements'
  resources :districts, :path => 'admin/districts'
  resources :grades, :path => 'admin/grades'
  resources :roles, :path => 'admin/roles'
  resources :users, :path => 'admin/users'
  resources :application_settings, :path => 'admin/settings'
  resources :staff_members, :path => 'admin/staff'

  resources :schools, :path => 'admin/schools' do
    resources :school_years, :path => 'years'
  end

  resources :students do
    get 'delete'
    post 'delete'

    resources :student_addresses, :path => 'addresses', :as => 'addresses' do
      resources :student_relationships, :path => 'contacts', :as => 'contacts'
    end

    resources :student_notes, :path => 'notes', :as => 'notes'
    resources :student_enrollments, :path => 'enrollments', :as => 'enrollments'

  end

end

app/models/student.rb
class Student < ApplicationRecord

  has_many :enrollments, :class_name => 'StudentEnrollment', :autosave => true
  has_many :addresses, :class_name => 'StudentAddress'
  has_many :notes, :class_name => 'StudentNote'
  has_many :relationships, through: :student_addresses, :class_name => 'StudentRelationship'

  accepts_nested_attributes_for :enrollments
  accepts_nested_attributes_for :addresses

  before_create :assign_student_id
  validates :first_name, presence: true, length: {maximum: 30}
  validates :middle_name, length: {maximum: 30}
  validates :last_name, presence: true, length: {maximum: 30}
  validates :suffix, length: {maximum: 5}
  validates :sex, length: {maximum: 1}

  def primary_address
    self.primary_address_id.nil? ? nil : StudentAddress.find(self.primary_address_id).address
  end

  def current_grade(format = 'long')
    current_enrollments = self.enrollments.includes(school_year_grade: [:grade]).where('admission_date <= ? and withdraw_date is null or withdraw_date >= ?', Date.today, Date.today)
    if current_enrollments.any?
      if current_enrollments.count == 1
        grade = current_enrollments.first.school_year_grade.grade
      else
        logger.warn('Student with multiple active enrollments ?', self.id)
        return format == 'long' ? 'MULTIPLE SCHOOLS!' : '!?!'
      end
      format == 'long' ? grade.title : grade.short_name
    else
      format == 'long' ? 'Not Registered' : 'NR'
    end
  end

  def is_registered?
    current_grade('short') == 'NR' ? false : true
  end

  def has_alert?
    true
  end

  def has_flagged_note?
    self.notes.where(:is_flagged => true).any?
  end

  def has_medical_alert?
    true
  end

  private

  def assign_student_id
    if self.student_id.nil?
      if Student.count == 0
        self.student_id = 1000
      else
        self.student_id = (Student.maximum(:student_id)) + 1
      end
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  include StudentHelper

  def index
    @q = Student.ransack(params[:q])
    @students = @q.result
  end

  def show
    @student = Student.includes(:addresses).find(params[:id])
    session[:student_id] = @student.id
  end

  def edit

  end

  def new
    unless can_new_student_be_admitted?
      flash[:error] = 'No students can be admitted for the currently selected school year.'
      redirect_to action: :index
    end

    @student = Student.new
    @student.enrollments << StudentEnrollment.new
    @student.addresses << StudentAddress.new do |sa|
      sa.address = Address.new
    end

    populate_select_lists
    @type = 'slow'
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student
    else
      populate_select_lists
      render 'new', :type => @type
    end
  end

  def delete
    get

    if request.post?
       if params[:agreement] == '1'
         @student.destory
       end
    end
  end

  private

  def build_new_student
    @student = Student.new
    if @student.nil?
      render :action
    end
  end

  def populate_select_lists
    @grades = SchoolYear.find(session['school_year_id']).grades
    @admission_codes = EnrollmentCode.where(:is_admission => true)

    if params[:type].nil? || get_user_pref == 'quick'
      @type = 'quick'
    else
      @type = 'slow'
    end
  end

  def student_params
    params.require(:student).permit(:id, :student_id, :first_name, :middle_name, :last_name, :suffix, :date_of_birth, :sex,
                                    { :enrollments_attributes => [:id, :student_id, :school_year_grade_id, :admission_date, :admission_code_id, :withdraw_date, :withdraw_code_id, :next_school_id] },
                                    { :addresses_attributes => [:id, :student_id, :address_id, :is_mailing, :is_residential, :is_bus_pickup, :is_bus_drop_off,
                                                                        { :address_attributes => [:id, :street, :city, :state, :zip_code, :phone_number] } ] })
  end

  def get_user_pref
    #todo: load preference
    'slow'
  end

  def get
    if params[:id]
      @student = Student.find(params[:id])
      else if params[:student_id]
             @student = Student.find(params[:student_id])
           end
    end
  rescue
    render_404
  end

end

app/helpers/student_helper.rb
module StudentHelper

  def student_tabs
    tabs = [{:name => 't1', :partial => 'students/info/info', :label => 'General'}]
  end

  def path_to_student_photo
    if @student.nil?
      #TODO: get path to image for student
    end
    image_path '/images/emptystudent.svg'
  end

  def can_new_student_be_admitted?
    unless SchoolYear.where(:id => active_school_year_id).first.grades.any?
      false
    end
    unless EnrollmentCode.where(:is_admission => true).any?
      false
    end
    true
  end
end

app/views/students/common/_header.html.haml
%h3
  = "#{student.formatted_full_name} (#{(student.student_number)})"
  %small
    = student.current_grade
    - if student.has_alert?
      &nbsp;
      %em{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'There is an alert for this student!'}
        = fa_icon 'warning', :class => 'text-yellow'
      - if student.has_flagged_note?
        &nbsp;
        %em{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'There is a flagged note for this student!'}
          = fa_icon 'flag', :class => 'text-warning'
      - if student.has_medical_alert?
        &nbsp;
        %em{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'There is a medical alert for this student!'}
          = fa_icon 'heartbeat', :class => 'text-danger'
.row
  .col-xs-12
    .btn-group
      .btn-group
        %button.btn.btn-default.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :type => 'button'}
          = fa_icon 'plus'
          New
          %span.caret
        %ul.dropdown-menu
          %li
            = link_to 'Address', new_student_address_path(student)
          %li
            = link_to 'Contact', new_student_address_contact_path(student, student.primary_address)
          %li
            = link_to 'Note', new_student_note_path(student)
      = link_to 'Edit', edit_student_path(student), :class => 'btn btn-default'
      .btn-group
        %button.btn.btn-default.dropdown-toggle{'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-toggle' => 'dropdown', :type => 'button'}
          = fa_icon 'cog'
          Options
          %span.caret
        %ul.dropdown-menu
          %li
            %a{:href => student_delete_path(student)}
              %span.text-danger Delete student
%br

app/views/students/common/_quickadmit.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title Basic Information
  .panel-body
    .form-group.row
      = f.label :student_name, :class => 'col-sm-2 col-form-label'
      .col-sm-3= f.text_field :first_name, :class => 'form-control', :placeholder => 'First'
      .col-sm-2= f.text_field :middle_name, :class => 'form-control', :placeholder => 'Middle'
      .col-sm-3= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last'
      .col-sm-2= f.text_field :suffix, :class => 'form-control', :placeholder => 'Suffix'
    .form-group.row
      = f.label :date_of_birth, :class => 'col-sm-2 col-form-label'
      .col-sm-3= f.text_field :date_of_birth, :class => 'form-control', :placeholder => 'MM/DD/YYYY'
      -#.col-sm-3= bs_text_field(f, :date_of_birth)

.panel.panel-primary
  .panel-heading
    %h3.panel-title Admission Information
  .panel-body
    = f.fields_for :enrollments do |ff|
      .form-group.row
        = f.label :student_name, :class => 'col-sm-2 col-form-label'
        .col-sm-3= f.text_field :first_name, :class => 'form-control', :placeholder => 'First'
        .col-sm-2= f.text_field :middle_name, :class => 'form-control', :placeholder => 'Middle'
        .col-sm-3= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last'
        .col-sm-2= f.text_field :suffix, :class => 'form-control', :placeholder => 'Suffix'
      .form-group.row
        = f.label :date_of_birth, :class => 'col-sm-2 col-form-label'
        .col-sm-3= f.text_field :date_of_birth, :class => 'form-control', :placeholder => 'MM/DD/YYYY'
        -#.col-sm-3= bs_text_field(f, :date_of_birth)

app/views/students/common/_sidebar.html.haml
.list-group
  %a.list-group-item.list-group-item-action{href: student_path(student), :class => ('active' if controller?('students');)}
    %i.fa.fa-wpforms
    Information
  %a.list-group-item.list-group-item-action{href: student_addresses_path(student), :class => ('active' if controller?('student_addresses') or controller?('student_relationships');)}
    %i.fa.fa-home
    Addresses and Contacts
  %a.list-group-item.list-group-item-action{href: student_notes_path(student), :class => ('active' if controller?('student_notes');)}
    %i.fa.fa-sticky-note
    Notes
  %a.list-group-item.list-group-item-action{href: student_enrollments_path(student), :class => ('active' if controller?('student_enrollments');)}
    %i.fa.fa-graduation-cap
    Enrollment History

app/views/students/common/_slowadmit.html.haml
.panel.panel-primary
  .panel-heading
    %h3.panel-title Basic Information
  .panel-body
    .form-group.row
      = f.label :student_name, :class => 'col-sm-2 col-form-label'
      .col-sm-3= f.text_field :first_name, :class => 'form-control', :placeholder => 'First'
      .col-sm-2= f.text_field :middle_name, :class => 'form-control', :placeholder => 'Middle'
      .col-sm-3= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last'
      .col-sm-2= f.text_field :suffix, :class => 'form-control', :placeholder => 'Suffix'
    .form-group.row
      = f.label :date_of_birth, :class => 'col-sm-2 col-form-label'
      .col-sm-3= f.text_field :date_of_birth, :class => 'form-control', :placeholder => 'MM/DD/YYYY'
      -#.col-sm-3= bs_text_field(f, :date_of_birth)

.panel.panel-primary
  .panel-heading
    %h3.panel-title Admission Information
  .panel-body
    = f.fields_for :enrollments do |ff|
      .form-group.row
        = f.label :student_name, :class => 'col-sm-2 col-form-label'
        .col-sm-3= f.text_field :first_name, :class => 'form-control', :placeholder => 'First'
        .col-sm-2= f.text_field :middle_name, :class => 'form-control', :placeholder => 'Middle'
        .col-sm-3= f.text_field :last_name, :class => 'form-control', :placeholder => 'Last'
        .col-sm-2= f.text_field :suffix, :class => 'form-control', :placeholder => 'Suffix'
      .form-group.row
        = f.label :date_of_birth, :class => 'col-sm-2 col-form-label'
        .col-sm-3= f.text_field :date_of_birth, :class => 'form-control', :placeholder => 'MM/DD/YYYY'
        -#.col-sm-3= bs_text_field(f, :date_of_birth)