config/routes.rb
Rails.application.routes.draw do

  root :to => 'home#index', :as => 'home'
  get 'grades' => 'home#grades', :as => 'grades'
  get 'help' => 'help#index', :as => 'help'
  get 'reports' => 'reports#index', :as => 'reports'

  devise_for :users, :path_prefix => 'security'

  resources :announcements, :path => 'admin/announcements'
  resources :districts, :path => 'admin/districts'
  resources :grades, :path => 'admin/grades'
  resources :roles, :path => 'admin/roles'
  resources :users, :path => 'admin/users'
  resources :application_settings, :path => 'admin/settings'
  resources :staff_members, :path => 'admin/staff'

  resources :schools, :path => 'admin/schools' do
    resources :school_years, :path => 'years'
  end

  resources :students do
    get 'delete'
    post 'delete'

    resources :student_addresses, :path => 'addresses', :as => 'addresses' do
      resources :student_relationships, :path => 'contacts', :as => 'contacts'
    end

    resources :student_notes, :path => 'notes', :as => 'notes'
    resources :student_enrollments, :path => 'enrollments', :as => 'enrollments'

  end

end

app/views/layouts/partials/_alerts.html.haml
- if flash[:info]
  .alert.alert-info= flash[:info]
- if flash[:error]
  .alert.alert-warning= flash[:error]
- if flash[:success]
  .alert.alert-success= flash[:success]
- if flash[:alert]
  .alert.alert-info= flash[:alert]

app/views/layouts/partials/_footer.html.haml
%span= "© #{Time.now.year} - MythCoders"

app/views/layouts/partials/_header.html.haml
- site_name = Genesis::INFO.app_name
- theme = cookies[:theme]
%title= page_title(site_name)

%meta{charset: 'utf-8'}
%meta{:content => 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type'}/
%meta{'http-equiv': 'X-UA-Compatible', content: 'IE=edge'}
%meta{name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1'}
%meta{name: 'description', content: "#{Genesis::INFO.versioned_name}"}
= csrf_meta_tags
= stylesheet_link_tag 'base', media: 'all'
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload', id: 'maincss'

- unless theme.nil?
  = stylesheet_link_tag "angle/themes/theme-#{theme}", media: 'all'

= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/partials/_offsidebar.html.haml
- theme = cookies[:theme]
%nav
  %div{:role => 'tabpanel'}
    -#%ul.nav.nav-tabs.nav-justified{:role => "tablist"}
    -#  %li.active{:role => "presentation"}
    -#    %a{"aria-controls" => "app-settings", "data-toggle" => "tab", :href => "#app-settings", :role => "tab"}
    -#      %em.icon-equalizer.fa-lg
    .tab-content
      #app-settings.tab-pane.fade.in.active{:role => 'tabpanel'}
        %h3.text-center.text-thin Preferences
        .p
          %h4.text-muted.text-thin Themes
          .table-grid.mb
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'a'}
                  %input{:checked => ('checked' if theme == 'a'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-info
                    %span.color.bg-info-light
                  %span.color.bg-white
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'b'}
                  %input{:checked => ('checked' if theme == 'b'),:name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-green
                    %span.color.bg-green-light
                  %span.color.bg-white
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'c'}
                  %input{:checked => ('checked' if theme == 'c'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-purple
                    %span.color.bg-purple-light
                  %span.color.bg-white
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'd'}
                  %input{:checked => ('checked' if theme == 'd'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-danger
                    %span.color.bg-danger-light
                  %span.color.bg-white
          .table-grid.mb
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'e'}
                  %input{:checked => ('checked' if theme == 'e'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-info-dark
                    %span.color.bg-info
                  %span.color.bg-gray-dark
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'f'}
                  %input{:checked => ('checked' if theme == 'f'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-green-dark
                    %span.color.bg-green
                  %span.color.bg-gray-dark
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'g'}
                  %input{:checked => ('checked' if theme == 'g'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-purple-dark
                    %span.color.bg-purple
                  %span.color.bg-gray-dark
            .col.mb
              .setting-color
                %label{'data-change-theme' => 'h'}
                  %input{:checked => ('checked' if theme == 'h'), :name => 'setting-theme', :type => 'radio'}
                  %span.icon-check
                  %span.split
                    %span.color.bg-danger-dark
                    %span.color.bg-danger
                  %span.color.bg-gray-dark
        .p
          %h4.text-muted.text-thin Layout
          .clearfix
            %p.pull-left Fixed
            .pull-right
              %label.switch
                %input#chk-fixed{'data-toggle-state' => 'layout-fixed', :type => 'checkbox'}/
                %span
          .clearfix
            %p.pull-left Boxed
            .pull-right
              %label.switch
                %input#chk-boxed{'data-toggle-state' => 'layout-boxed', :type => 'checkbox'}/
                %span
          .clearfix
            %p.pull-left RTL
            .pull-right
              %label.switch
                %input#chk-rtl{:type => 'checkbox'}/
                %span
        .p
          %h4.text-muted.text-thin Aside
          .clearfix
            %p.pull-left Collapsed
            .pull-right
              %label.switch
                %input#chk-collapsed{'data-toggle-state' => 'aside-collapsed', :type => 'checkbox'}/
                %span
          .clearfix
            %p.pull-left Collapsed Text
            .pull-right
              %label.switch
                %input#chk-collapsed-text{'data-toggle-state' => 'aside-collapsed-text', :type => 'checkbox'}/
                %span
          .clearfix
            %p.pull-left Float
            .pull-right
              %label.switch
                %input#chk-float{'data-toggle-state' => 'aside-float', :type => 'checkbox'}/
                %span
          .clearfix
            %p.pull-left Hover
            .pull-right
              %label.switch
                %input#chk-hover{'data-toggle-state' => 'aside-hover', :type => 'checkbox'}/
                %span
          .clearfix
            %p.pull-left Show Scrollbar
            .pull-right
              %label.switch
                %input#chk-hover{'data-target' => '.sidebar', 'data-toggle-state' => 'show-scrollbar', :type => 'checkbox'}/
                %span

app/views/layouts/partials/_sidebar.html.haml
.aside-inner
  %nav.sidebar{'data-sidebar-anyclick-close' => ''}
    %ul.nav
      %li.has-user-block
        #user-block.collapse
          .item.user-block
            .user-block-picture
              .user-block-status
                %img.img-thumbnail.img-circle{:alt => 'Avatar', :height => '60', :src => '', :width => '60'}
                .circle.circle-success.circle-lg
            .user-block-info
              %span.user-block-name Hello, User!
              %span.user-block-role System Administrator
      = render_menu :sidebar
      -#%li{:class => "#{'active' if controller?('maps')}"}
      -#  %a{'data-toggle' => 'collapse', :href => '#administration', :title => 'Administration'}
      -#    %em.icon-settings
      -#    %span{'data-localize' => 'sidebar.nav.map.MAP'} Administration
      -#  %ul#administration.nav.sidebar-subnav.collapse
      -#    %li{:class => "#{'active' if controller?('announcements');}"}
      -#      = link_to 'Announcements', announcements_path
      -#    %li{:class => "#{'active' if controller?('calendars');}"}
      -#      = link_to 'Calendars', calendars_path
      -#    %li{:class => "#{'active' if controller?('courses');}"}
      -#      = link_to 'Courses', courses_path
      -#    %li{:class => "#{'active' if controller?('districts');}"}
      -#      = link_to 'Districts', districts_path
      -#    %li{:class => "#{'active' if controller?('grades');}"}
      -#      = link_to 'Grade Levels', grades_path
      -#    %li{:class => "#{'active' if controller?('schools');}"}
      -#      = link_to 'Marking Periods', schools_path
      -#    %li{:class => "#{'active' if controller?('maps');}"}
      -#      = link_to 'Schools', schools_path
      -#    %li{:class => "#{'active' if controller?('roles');}"}
      -#      = link_to 'User Roles', roles_path
      -#    %li{:class => "#{'active' if controller?('users');}"}
      -#      = link_to 'Users', users_path
      -#    %li{:class => "#{'active' if controller?('settings');}"}
      -#      = link_to 'Control Panel', settings_path

app/views/layouts/partials/_topnavbar.html.haml
%nav.navbar.topnavbar{:role => 'navigation'}
  .navbar-header
    %a.navbar-brand{:href => home_path}
      .brand-logo
        %img.img-responsive{:alt => "#{Genesis::INFO.app_name} Logo", :src => "#{image_path('angle/logo.png')}"}
      .brand-logo-collapsed
        %img.img-responsive{:alt => "#{Genesis::INFO.app_name} Logo", :src => "#{image_path('angle/logo-single.png')}"}
  .nav-wrapper
    %ul.nav.navbar-nav
      %li
        %a.hidden-xs{'data-toggle-state' => 'aside-collapsed', :href => '#', :title => 'Toggle sidebar'}
          %em= fa_icon 'navicon'
        %a.visible-xs.sidebar-toggle{'data-no-persist' => 'true', 'data-toggle-state' => 'aside-toggled', :href => '#', :title => 'Toggle sidebar'}
          %em= fa_icon 'navicon'
      %li
        %a{'data-search-open' => '', :href => '#', :title => 'Search'}
          %em= fa_icon 'search'
      %li
        - unless @student.nil?
          %a{:href => '#'}
            Student:
            Adkins, Justin M.
            - if @student.has_alert?
              &nbsp;
              %em{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'There is an alert for this student!'}
                = fa_icon 'warning', :class => 'text-yellow'
            - if @student.has_flagged_note?
              &nbsp;
              %em{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'There is a flagged note for this student!'}
                = fa_icon 'flag', :class => 'text-warning'
            - if @student.has_medical_alert?
              &nbsp;
              %em{'data-toggle': 'tooltip', 'data-placement': 'bottom', title: 'There is a medical alert for this student!'}
                = fa_icon 'heartbeat', :class => 'text-danger'
    %ul.nav.navbar-nav.navbar-right
      %li
        %a{'data-no-persist' => 'true', 'data-toggle-state' => 'offsidebar-open', :href => '#', :title => 'Preferences'}
          %em= fa_icon 'sliders'
      %li.dropdown.dropdown-list
        %a{'aria-expanded' => 'true', 'data-toggle' => 'dropdown', :href => '#'}
          %em.icon-bell
          .label.label-danger 11
        %ul.dropdown-menu
          %li
            .list-group
              %a.list-group-item{:href => '#'}
                .media-box
                  .pull-left
                    %em.fa.fa-users.fa-2x.text-success
                  .media-box-body.clearfix
                    %p.m0 Student Admissions
                    %p.m0.text-muted
                      %small 1 pending admission
              %a.list-group-item{:href => application_settings_path}
                .media-box
                  .pull-left
                    %em.fa.fa-wrench.fa-2x.text-info
                  .media-box-body.clearfix
                    %p.m0 System Updates
                    %p.m0.text-muted
                      %small= "Updates are available for #{Genesis::INFO.app_name}"
              %a.list-group-item{:href => '#'}
                %small View all notifications
      %li.hidden-xs
        = link_to destroy_user_session_path, :method=>'delete', :title => 'Sign out' do
          %em= fa_icon 'sign-out'
  %form.navbar-form{:action => 'search.html', :role => 'search'}
    .form-group.has-feedback
      %input.form-control{:placeholder => 'Type and hit enter ...', :type => 'text'}
      .fa.fa-times.form-control-feedback{'data-search-dismiss' => ''}
    %button.hidden.btn.btn-default{:type => 'submit'} Submit